### ISSUE TITLE
Upgrade to Ubuntu 20.04

### ISSUE THREAD

**Issue by rickb777** [hbt/git-forks-analysis#2]
Just a minor thing: the Dockerfile uses 16.04 which is now out its main Long Term Support support (although it will have maintenance for a few years yet).

Please would you upgrade to 20.04.

**Comment by hbt** [comment]
The reason Docker is used is precisely not to have to upgrade dependencies every few years. 

Even if the apt repositories and mirror disappear and the build stops working, the docker image layers will still be available and *work*.

I treat Docker on this project as a big fat binary that will survive through time unchanged.

Of course, you're welcome to fork it and I'd add a reference in the README
